# this rule used for setting a component data/equation names
# component name:
# DATA:
#   data symbol defined in TableData: new symbol
# EQUATIONS:
#   equation symbol defined in TableEquations: new symbol

CO2:
  DATA:
    critical-pressure: Pc
    Tc: Tc
    AcFa: AcFa
  EQUATIONS:
    CUSTOM-REF-1::vapor-pressure: VaPr
    CUSTOM-REF-1::ideal-gas-heat-capacity: Cp_IG
C6H6:
  DATA:
    critical-pressure: Pc
    Tc: Tc
    AcFa: AcFa
  EQUATIONS:
    CUSTOM-REF-1::vapor-pressure: VaPr
    CUSTOM-REF-1::ideal-gas-heat-capacity: Cp_IG
acetylene:
  DATA:
    Pc: Pc
    Tc: Tc
    AcFa: AcFa
  EQUATIONS:
    vapor-pressure: VaPr
EtOH:
  DATA:
    Pc: Pc1
    Tc: Tc2
    AcFa: AcFa3
  EQUATIONS:
    vapor-pressure: VaPr
MeOH:
  DATA:
    Pc: Pc
    critical-temperature: Tc
    AcFa: AcFa
  EQUATIONS:
    CUSTOM-REF-1::vapor-pressure: VaPr
    CUSTOM-REF-1::ideal-gas-heat-capacity: Cp_LIQ
n-butane:
  DATA:
    Pc: Pc
    Tc: Tc
    AcFa: AcFa
  EQUATIONS:
    vapor-pressure: VaPr
NRTL:
  DATA:
    Alpha: alpha_i_j
  EQUATIONS:
    nrtl_tau: tau_i_j
toluene:
  DATA:
    Pc: Pc
    Tc: Tc
    AcFa: AcFa
  EQUATIONS:
    vapor-pressure: VaPr